name: rela
description: "A Flutter chat realtime application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State & Network
  provider: ^6.1.2
  http: ^1.1.0
  web_socket_channel: ^3.0.1

  # Media & Storage
  image_picker: 1.0.7
  path_provider: 2.1.2
  permission_handler: ^11.0.1

  agora_rtc_engine: ^6.5.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/
